[package]
name = "valorant-discord-rich-presence"
version = "0.1.0-beta2"
edition = "2021"
publish = false
authors = [ "NyCode <me@nycode.dev>" ]
description = "Show what you are doing in valorant in your discord rich presence."
repository = "https://github.com/NyCodeGHG/valorant-discord-rich-presence"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
notify = "4.0.17"
reqwest = { version = "0.11", features = ["json"] }
lazy_static = "1.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
native-tls = "0.2"
base64 = "0.13"
http = "0.2"
serde_tuple = "0.5"
discord-sdk = "0.2.1"
nonzero_ext = "0.3.0"
async-recursion = "1.0.0"
